updated: '2026-02-19T00:30:15.322855'
hosts:
- name: termux
  host: 127.0.0.1
  port: 8022
  username: u0_a475
  password: admin
  private_key_path: null
  remark: Termux设备
  purpose: termux
  os_version: ''
  enabled: true
- name: test-server
  host: 192.168.1.100
  port: 22
  username: root
  password: test123
  private_key_path: null
  remark: ''
  purpose: ''
  os_version: Unknown
  enabled: true
